FROM ubuntu:22.04

RUN mkdir backend
WORKDIR backend

RUN apt-get update -y && \
    apt install python3-pip -y && \
    pip install -U Flask && \
    pip install -U flask-cors

COPY backend/TTC.py TTC.py
COPY backend/app.py app.py

EXPOSE 5000

CMD ["python3", "app.py"]